version: '3.8'

services:
  fuseki:
    image: secoresearch/fuseki:latest
    container_name: promcode-fuseki
    ports:
      - "127.0.0.1:3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_DATASET_1=dataset
      - ENABLE_UPDATE=true
    volumes:
      - fuseki-data:/fuseki-data
    networks:
      - promcode-network

  promcode-server:
    build: .
    container_name: promcode-server
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - fuseki
    environment:
      - LYO_STORE_SPARQL_QUERY_ENDPOINT=http://fuseki:3030/ds/sparql
      - LYO_STORE_SPARQL_UPDATE_ENDPOINT=http://fuseki:3030/ds/update
    networks:
      - promcode-network

volumes:
  fuseki-data:

networks:
  promcode-network:
    driver: bridge
