<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2022 Contributors to the Eclipse Foundation
 
 See the NOTICE file(s) distributed with this work for additional
 information regarding copyright ownership.
 
 This program and the accompanying materials are made available under the
 terms of the Eclipse Distribution License 1.0 which is available at
 http://www.eclipse.org/org/documents/edl-v10.php.
 
 SPDX-License-Identifier: BSD-3-Simple

 This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@page import="org.eclipse.lyo.oslc4j.core.model.Link" %>
<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="org.eclipse.lyo.oslc4j.core.model.OslcConstants"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcName"%>
<%@page import="java.lang.reflect.Method"%>
<%@page import="java.net.URI"%>
<%@page import="java.util.Collection"%>
<%@page import="java.util.Date"%>
<%@page import="java.util.HashSet"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Iterator"%>
<%@page import="java.util.Map"%>
<%@page import="javax.xml.namespace.QName"%>
<%@page import="jakarta.ws.rs.core.UriBuilder"%>

<%@page import="org.eclipse.lyo.oslc.domains.promcode.Artifact"%>
<%@page import="org.eclipse.lyo.oslc.domains.promcode.Oslc_promcodeDomainConstants"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
  Artifact aArtifact = (Artifact) request.getAttribute("aArtifact");
%>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= aArtifact.toString() %></title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">
</head>

<body>

<!-- Begin page content -->
<div>
    <% Method method = null; %>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getIsPartOf"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="isPartOf"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <%
        if ((aArtifact.getIsPartOf() == null) || (aArtifact.getIsPartOf().getValue() == null)) {
            out.write("<em>null</em>");
        }
        else {
            %>
            <jsp:include page="/org/oasis/oslc/promcode/server/artifacttohtml.jsp">
                <jsp:param name="resourceUri" value="<%=aArtifact.getIsPartOf().getValue()%>"/> 
                </jsp:include>
            <%
        }
        %>
        
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getProducedFor"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="producedFor"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <ul>
        <%
        Iterator<String> producedForItr = aArtifact.getProducedFor().iterator();
        while(producedForItr.hasNext()) {
            out.write("<li>" + producedForItr.next().toString() + "</li>");
        }
        %>
        </ul>
        
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getTargets"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="targets"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <ul>
        <%
        for(Link next : aArtifact.getTargets()) {
            if (next.getValue() == null) {
                out.write("<li>" + "<em>null</em>" + "</li>");
            }
            else {
                %>
                <li>
                <jsp:include page="/org/oasis/oslc/promcode/server/measuretohtml.jsp">
                    <jsp:param name="resourceUri" value="<%=next.getValue()%>"/> 
                    </jsp:include>
                </li>
                <%
            }
        }
        %>
        </ul>
        
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getDescription"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource."><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <%
        if (aArtifact.getDescription() == null) {
            out.write("<em>null</em>");
        }
        else {
            out.write(aArtifact.getDescription().toString());
        }
        %>
        
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getIdentifier"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title=""><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <%
        if (aArtifact.getIdentifier() == null) {
            out.write("<em>null</em>");
        }
        else {
            out.write(aArtifact.getIdentifier().toString());
        }
        %>
        
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getSource"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="source"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <%
        if (aArtifact.getSource() == null) {
            out.write("<em>null</em>");
        }
        else {
            out.write(aArtifact.getSource().toString());
        }
        %>
        
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getTitle"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="title"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <%
        if (aArtifact.getTitle() == null) {
            out.write("<em>null</em>");
        }
        else {
            out.write(aArtifact.getTitle().toString());
        }
        %>
        
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <% method = Artifact.class.getMethod("getSequenceNumber"); %>
        <dt><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="sequenceNumber"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
        <dd>
        <%
        if (aArtifact.getSequenceNumber() == null) {
            out.write("<em>null</em>");
        }
        else {
            out.write(aArtifact.getSequenceNumber().toString());
        }
        %>
        
        </dd>
    </dl>
</div>
<%
Map<QName, Object> extendedProperties = aArtifact.getExtendedProperties();
if (!extendedProperties.isEmpty()) {
%>
    <div>
    <%
    for (Map.Entry<QName, Object> entry : extendedProperties.entrySet()) 
    {
        QName key = entry.getKey();
        Object value = entry.getValue();
    %>
    <dl class="row">
        <dt  class="col-sm-2 text-end"><a href="<%=key.getNamespaceURI() + key.getLocalPart() %>" style="text-decoration-style: dashed;" target="_blank" rel="noopener noreferrer" title="<%=key.getLocalPart()%>"><%=key.getLocalPart()%></a></dt>
        <dd class="col-sm-9"><%= value.toString()%></dd>
    </dl>
    <%
    }
    %>
    </div>
<%
}
%>
</body>
</html>
